baseURL: "https://nabarun.dev/"
languageCode: "en-us"
title: "Nabarun Pal"
theme: "cactus"
params:
  description: "Open Source. Distributed Systems. Infrastructure."
  showMainSection: false
  mainSection: "posts"
  mainSectionTitle: Posts
  colortheme: "classic"
  rss: true
  mathjax: true
  social:
    - name: GitHub
      link: https://github.com/palnabarun
    - name: Twitter
      link: https://twitter.com/theonlynabarun
    - name: LinkedIn
      link: https://linkedin.com/in/palnabarun
  taxonomies:
    tags: tags
  css:
    - css/custom.css
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: true
    style: monokai
enableEmoji: true
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Speaking"
      url: "/speaking"
      weight: 3
